//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintWebCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assunto
    {
        public assunto()
        {
            this.Aluno = new HashSet<Aluno>();
            this.Referencia = new HashSet<Referencia>();
        }
    
        public int AssuntoID { get; set; }
        public string DescAssunto { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual ICollection<Referencia> Referencia { get; set; }
    }
}
