//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintWebCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.Aluno = new HashSet<Aluno>();
        }
    
        public int DepartamentoID { get; set; }
        public string DepartamentoNome { get; set; }
        public string DepartamentoSigla { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
    }
}
