//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintWebCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Aluno = new HashSet<Aluno>();
        }
    
        public int Enderecoid { get; set; }
        public string EnderecoRua { get; set; }
        public Nullable<int> EnderecoNumero { get; set; }
        public string EnderecoBairro { get; set; }
        public string EnderecoComplemento { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
    }
}
