//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintWebCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public materia()
        {
            this.Aluno_Materia = new HashSet<Aluno_Materia>();
        }
    
        public int MateriaID { get; set; }
        public string MateriaNome { get; set; }
    
        public virtual ICollection<Aluno_Materia> Aluno_Materia { get; set; }
    }
}
