//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintWebCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaAutor
    {
        public int ReferenciaAutorID { get; set; }
        public int ReferenciaID { get; set; }
        public int AutorID { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Referencia Referencia { get; set; }
    }
}
